clear;
clc;
close all;
addpath(genpath('Sims/'));
addpath(genpath('../functions'))

struct_folger_sim = importdata('Sims/Folger_spect.txt');
struct_inv_verst_sim = importdata('Sims/inv_verst.txt', ' ');
struct_niinv_verst_sim = importdata('Sims/niinv_verst.txt', ' ');

fig_folger = figure('Name', 'Folgerschaltung');
bodePlot_din461(fig_folger,struct_folger_sim.data(:,1),...
    struct_folger_sim.data(:,4),...
    struct_folger_sim.data(:,3),...
    struct_folger_sim.data(:,2), '', true);
legend('Simulation', 'Messung');


fig_inv_verst = figure('Name', 'invertierender Verstärker');
bodePlot_din461(fig_inv_verst,struct_inv_verst_sim.data(:,1),...
    struct_inv_verst_sim.data(:,12),...
    struct_inv_verst_sim.data(:,8),...
    struct_inv_verst_sim.data(:,2), '', false);

bodePlot_din461(fig_inv_verst,struct_inv_verst_sim.data(:,1),...
    struct_inv_verst_sim.data(:,12+1),...
    struct_inv_verst_sim.data(:,8+1),...
    struct_inv_verst_sim.data(:,2+1), '', false);

bodePlot_din461(fig_inv_verst,struct_inv_verst_sim.data(:,1),...
    struct_inv_verst_sim.data(:,12+2),...
    struct_inv_verst_sim.data(:,8+2),...
    struct_inv_verst_sim.data(:,2+2), '', false);

bodePlot_din461(fig_inv_verst,struct_inv_verst_sim.data(:,1),...
    struct_inv_verst_sim.data(:,12+3),...
    struct_inv_verst_sim.data(:,8+3),...
    struct_inv_verst_sim.data(:,2+3), '', true);
xlim([1 1e5])
subplot(2,1,1)
xlim([1 1e5])
ylim([-10 100])
legend('sim1', 'sim2','sim3', 'sim4')

fig_niinv_verst = figure('Name', 'nicht invertierender Verstärker');
bodePlot_din461(fig_niinv_verst,struct_niinv_verst_sim.data(:,1),...
    struct_niinv_verst_sim.data(:,16),...
    struct_niinv_verst_sim.data(:,12),...
    struct_niinv_verst_sim.data(:,2), '', false);

bodePlot_din461(fig_niinv_verst,struct_niinv_verst_sim.data(:,1),...
    struct_niinv_verst_sim.data(:,16+1),...
    struct_niinv_verst_sim.data(:,12+1),...
    struct_niinv_verst_sim.data(:,2+1), '', false);

bodePlot_din461(fig_niinv_verst,struct_niinv_verst_sim.data(:,1),...
    struct_niinv_verst_sim.data(:,16+2),...
    struct_niinv_verst_sim.data(:,12+2),...
    struct_niinv_verst_sim.data(:,2+2), '', false);

bodePlot_din461(fig_niinv_verst,struct_niinv_verst_sim.data(:,1),...
    struct_niinv_verst_sim.data(:,16+3),...
    struct_niinv_verst_sim.data(:,12+3),...
    struct_niinv_verst_sim.data(:,2+3), '', true);

legend('sim1', 'sim2','sim3', 'sim4')